#!/bin/bash
# autogenrated with mkscriptu at Sun Nov 10 05:28:51 EST 2019 

# really not needed as should have been done 
. setup

#loc="/home/scripts/exitutil"

#loc="/home/marchywka/scripts/exitutil"

some_hist()
{
cat - << xxx---xxx
needed more current version due to bug
ls -al `which -a exiftool `
-rwxr-xr-x 1 root root 261955 Jan 23  2016 /usr/bin/exiftool
-r-xr-xr-x 1 root root 292902 Nov  5 05:39 /usr/local/bin/exiftool
exiftool -struct -f -x -ee xxx
ls -atl `which -a exiftool `
xxx---xxx
}
set_exif_tool()
{
EXIF=""
# of course, this does absolutely nothing as the base name
# is used and bash just follows search path ... 
#EXIF=`ls -atl \`which -a exiftool \` | head -n 1| awk '{print $NF}' `
NEXIF=`which -a exiftool  | wc -l  `
if  [ "$NEXIF" != "0" ]
then
EXIF=`ls -t \`which -a exiftool \` | head -n 1 | awk '{print $1}' `
echo wtf exit = $EXIF
choices=`ls -alt \`which -a exiftool\` | wc -l`
if [ "$choices" != "1" ]
then
#echo multiple exids, `ls -atl `which -a exiftool | wc -l`
echo multiple exifs  | smsg
fi
fi  # which 

if [ "$EXIF" == "" ]
then 
echo no tool found $NEXIF | smsg
EXIF="echo no tool found "
fi
}

set_exif_tool 2> /dev/null
FLAGS="-struct -f -x -ee "

help()
{
echo Usage $0 
grep "^if.*==.*\"-" $0
}
while [ "$*" != "" ]
do
start="$*"
if [ "$1" == "-help" ]
then
help
shift
fi
if [ "$1" == "-listold" ]
then
echo using $EXIF $FLAGS "$2"
$EXIF $FLAGS "$2"
#echo did $EXIF $FLAGS "$2"
shift
shift
fi
if [ "$1" == "-list" ]
then
EXDIR="/home/ubuntu/dev/exiftool/Image-ExifTool-11.75"
fn=`readlink -f "$2"`
cd "$EXDIR"
./exiftool $FLAGS "$fn"
#echo using $EXIF $FLAGS "$2"
#$EXIF $FLAGS "$2"
##echo did $EXIF $FLAGS "$2"
shift
shift
fi


if [ "$*" == "$start" ]
then
help
exit -1
fi

done


