#ifndef MJM_GOOG_BOOKS_H__
#define MJM_GOOG_BOOKS_H__

#include "mjm_globals.h"
#include "mjm_thread_util.h"
#include "mjm_bibtex_entry.h"

//#include "mjm_block_matrix.h"
#include "mjm_instruments.h"
#include "mjm_strings.h"
#include "mjm_string_kvp.h"
#include "mjm_worm_blob.h"
#include "mjm_collections.h"
//#include "mjm_tokenized_collections.h"
#include "mjm_canned_methods.h"

#include "mjm_pawnoff.h"
#include "mjm_strings.h"
#include "mjm_string_kvp.h"
#include "mjm_generic_iterators.h"



#include <map> 
#include <vector> 
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <string>
#include <fstream>
#include <signal.h>
#include <stdlib.h>
#include <stdint.h>


/*
<one line to give the program's name and a brief idea of what it does.>


Conceived and written by Mike Marchywka from 2026 to present.
See dates in individual code pieces as they were 
generated from my wizards. 
Copyright (C) <year> <name of author>


This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see <http://www.gnu.org/licenses/>.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
   EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

/*
@software{,
  author = {Michael J Marchywka},
  city = {Talking Rock GA 30175 USA},
  title = {},
abstract={},
institution={},
license={Knowledge sir should be free to all },
publisher={Mike Marchywka},
email={marchywka@hotmail.com},
authorid={orcid.org/0000-0001-9237-455X},
  filename={mjm_goog_books.h},
  url = {},
  version = {0.0.0},
  date-started={2026-02-23},
}
*/

// Mon Feb 23 07:17:22 PM EST 2026
// generated by /home/documents/cpp/scripts/cpputil -classhdr mjm_goog_books    at Mon Feb 23 07:17:22 PM EST 2026
// QUICKCOMPILE  g++  -MMD -MF mjm_goog_books.deps  -Wall -Wno-misleading-indentation  -std=gnu++11 -DTEST_MJM_GOOG_BOOKS -I. -I../../mjm/hlib -I../../mjm/num    -gdwarf-3 -O0  -x c++ mjm_goog_books.h  -o mjm_goog_books.out -lpthread -lreadline

mjm_global_credits::credit __credit__mjm_goog_books("mjm_goog_books" , "  ");

template <class Tr>
class mjm_goog_books 
{
 typedef mjm_goog_books Myt;
 typedef typename Tr::IdxTy IdxTy;
 typedef typename Tr::D D;
 typedef typename Tr::StrTy StrTy;
 typedef typename Tr::Ss Ss;
 typedef typename Tr::IsTy IsTy;
 typedef typename Tr::OsTy OsTy;
 typedef typename Tr::Ofs Ofs;
//typedef typename Tr::FlagTy; 
// typedef typename Tr::MyBlock  MyBlock;

// TYPEDEF 
enum { BAD=~0};
//typedef mjm_canned_methods Canned;
typedef mjm_ragged_table Ragged;
typedef Ragged::Line Line;
typedef std::map<StrTy, Ragged> RaggedMap;
typedef std::vector<StrTy> Words;
typedef mjm_string_base_params<Tr> BaseParams;
typedef mjm_pawnoff<Tr> Hand;
typedef std::map<StrTy,StrTy> Kvp;

typedef mjm_strings StrUtil;

typedef mjm_blob<Tr> Blob;

typedef mjm_bibtex_entry<Tr> BibEntry;
typedef mjm_bibtex_entry_map<Tr> BibMap;
typedef mjm_bibtex_entry_map<Tr> BibEntryMap;



/* /
wget -O xxx -S -v  --user=agent "TooBib ( marchywka@hotmail.com )"  "https://www.googleapis.com/books/v1/volumes?q=isbn:$isbn&key=AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc"
wget -O xxx -S -v  --user-agent "TooBib ( marchywka@hotmail.com )"  "https://www.googleapis.com/books/v1/volumes?q=isbn:$isbn&key=AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc"
--2026-02-23 19:19:15--  https://www.googleapis.com/books/v1/volumes?q=isbn:9780702060588&key=AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc
Resolving www.googleapis.com (www.googleapis.com)... 2607:f8b0:4002:c03::5f, 2607:f8b0:4002:c05::5f, 2607:f8b0:4002:c09::5f, ...
Connecting to www.googleapis.com (www.googleapis.com)|2607:f8b0:4002:c03::5f|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Content-Type: application/json; charset=UTF-8
  Vary: X-Origin
  Vary: Referer
  Date: Tue, 24 Feb 2026 00:19:16 GMT
  Server: ESF
  X-XSS-Protection: 0
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  Accept-Ranges: none
  Vary: Origin,Accept-Encoding
  Transfer-Encoding: chunked
Length: unspecified [application/json]
Saving to: ‘xxx’

xxx                     [ <=>                ]   6.62K  --.-KB/s    in 0.005s  

2026-02-23 19:19:16 (1.28 MB/s) - ‘xxx’ saved [6780]

 wget -O xxx -S -v  --user-agent "TooBib ( marchywka@hotmail.com )"  "https://www.googleapis.com/books/v1/volumes/UDwPBAAAQBAJ?key=AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc"



*/

// API

public:
mjm_goog_books() {Init(); }
mjm_goog_books(const StrTy & sin,const IdxTy flags) {Init(sin,flags); }
mjm_goog_books(const Ragged & r,const IdxTy start, const IdxTy first,const IdxTy flags ) {Init(r,start,first,flags);}

// first fetch into fn, parse into fn2 , and then save in fn
IdxTy by_goog_id(const StrTy & fn2, const StrTy & fn, const StrTy & id, const IdxTy flags)
{ return ByGoogId(fn2,fn,id,flags); } 
IdxTy by_isbn(const StrTy & fnbib, const StrTy & fnraw, const StrTy & fnparsed, const StrTy & id, const IdxTy flags)
{ return ByIsbn(fnbib,fnraw,fnparsed,id,flags); } 



void load(const StrTy & sin,const IdxTy flags) {Init(sin,flags); }
void load(const Ragged & r,const IdxTy start, const IdxTy first,const IdxTy flags ) {Init(r,start,first,flags);}
void save(const StrTy & fn,const StrTy &s) {Save(fn,s); }

StrTy xxx_test(const StrTy & sin, const IdxTy flags) 
{ return XXX_test(sin,flags); } 
~mjm_goog_books() {}
StrTy dump(const IdxTy flags=0) { return Dump(flags); }
private:
int myatoi(const StrTy & s )const   { return mjm_canned_methods::myatoi(s.c_str()); }
int myatoi(const char * c) const  { return mjm_canned_methods::myatoi(c); }
static bool Bit(const IdxTy f, const IdxTy b) { return  ((f>>b)&1)!=0; }
// should loop over map now 
static void Set(IdxTy& f, const IdxTy b,const bool x) //const  
    { if (x) f|=(1<<b); else f&=~((1)<<b); }
StrTy Dump(const IdxTy flags=0) {Ss ss;  return ss.str(); }
typedef typename mjm_thread_util<Tr>::mutex_vector MutexVector;

enum { MAP_MU=0 , MU_SZ};
mutable MutexVector m_mutex_vector;
void EnterSerial(const IdxTy i)const  {  m_mutex_vector.enter_serial(i ); }
void ExitSerial(const IdxTy i)const  {  m_mutex_vector.exit_serial(i ); }
//m_mutex_vector = MutexVector(MU_SZ);


void Save(const StrTy & fn,const StrTy &s) {
// std::ofstream ofs(fn);

 } // Save
StrTy XXX_test(const StrTy & sin, const IdxTy flags) 
{
StrTy sout="";
MM_ERR(MMPR3(sin,flags,sout))
BaseParams kvp(sin);

return sout;
} // XXX_test

// wget -O xxx -S -v  --user-agent "TooBib ( marchywka@hotmail.com )"  "https://www.googleapis.com/books/v1/volumes/UDwPBAAAQBAJ?key=AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc"
IdxTy Wget(const StrTy & fn, const StrTy & url, const IdxTy flags=0)
{
StrTy cmd="wget -O "+fn+" -S -v --user-agent=\""+m_ua+"\" \""+url+"\"";
MM_ERR(MMPR(cmd))
StrTy d,d2;
hand().cmd_exec(d,StrTy(),cmd,16);
MM_ERR(MMPR(d))
const StrTy cmd2="grep -A 2  \"request sent,\" | grep HTTP | tail -n 1  | awk '{print $2}' ";
hand().cmd_exec(d2,d,cmd2,16);
const int rc=atoi(d2.c_str());
MM_ERR(MMPR3(rc,d2,cmd2))
return rc; 
} // Wget 


//wget -O xxx -S -v  --user-agent "TooBib ( marchywka@hotmail.com )"  "https://www.googleapis.com/books/v1/volumes?q=isbn:$isbn&key=AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc"
IdxTy ByIsbn(const StrTy & fnbib, const StrTy & fnraw, const StrTy & fnparsed, const StrTy & isbn, const IdxTy flags)
{ 
MM_ERR(MMPR4(fnbib,fnraw,fnparsed,isbn)) 
StrTy url= "https://www.googleapis.com/books/v1/volumes?q=isbm:"+isbn+"&key="+m_key;
IdxTy rc=Wget(fnraw,url,flags);
MM_ERR(MMPR(rc))
Kvp m;
//IdxTy NewDefaultJsonScraper2(Kvp & m, Ragged & j,  const StrTy & fntemp2, const StrTy & fntemp, const StrTy & sep,const IdxTy llim, const IdxTy flags )
Ragged j;
// parse fntemp into fntemp2 and load into j
NewDefaultJsonScraper2(m,j,fnparsed,fnraw,"_",0,0);
MM_ERR(MMPR(j.dump()))
StrTy name="xxx";
FixMap(m);
if (m.end()!=m.find("id")) name=m["id"];

BibEntry bib;
MakeBib(bib,fnbib,name,"book",m,flags); 
return 0; 
}  // ByIsbn

void FixMap(Kvp & m)
{
MM_LOOP(ii,m) { MM_ERR(MMPR2((*ii).first, (*ii).second)) } 

Add(m,"abstract","volumeinfo_description");
Add(m,"isbn","volumeinfo_industryidentifiers_identifier");
Add(m,"isbntypes","volumeinfo_industryidentifiers_type");
Add(m,"pages","volumeinfo_printedpagecount");
Add(m,"title","volumeinfo_title");
Add(m,"date","volumeinfo_publisheddate");
Add(m,"publisher","volumeinfo_publisher");
Add(m,"authors","volumeinfo_authors_authors");



} // FixMap


// first fetch into fn, parse into fn2 , and then save in fn
// not best for debug as it trashes original file.   
IdxTy ByGoogId(const StrTy &fn2, const StrTy & fn, const StrTy & id, const IdxTy flags)
{ 
MM_ERR(MMPR4(fn2,fn,id,flags)) 
StrTy url= "https://www.googleapis.com/books/v1/volumes/"+id+"?key="+m_key;
IdxTy rc=Wget(fn,url,flags);
MM_ERR(MMPR(rc))
Kvp m;
//IdxTy NewDefaultJsonScraper2(Kvp & m, Ragged & j,  const StrTy & fntemp2, const StrTy & fntemp, const StrTy & sep,const IdxTy llim, const IdxTy flags )
Ragged j;
// parse fntemp into fntemp2 and load into j
NewDefaultJsonScraper2(m,j,fn2,fn,"_",0,0);
StrTy name="xxx";
FixMap(m);
if (m.end()!=m.find("id")) name=m["id"];
if (m.end()==m.find("citeurl")) m["citeurl"]=url;
MM_ERR(MMPR(j.dump()))
BibEntry bib;
MakeBib(bib,fn,name,"book",m,flags); 
return 0; 

} 

// similar to synthesize() from med2bib_funcs 
bool Add(Kvp & m, const StrTy & d, const StrTy & s)
{ 
const auto ii=m.find(s);
if (ii==m.end()) return false; 
if (m.end()==m.find(d)) {   m[d]=m[s]; m.erase(ii); } 
return true; 
 }  // Add

 IdxTy MakeBib(BibEntry & bib, const StrTy & fnbib, const StrTy & name, const StrTy & type, const Kvp & kvp, const IdxTy flags=0)
{
//const bool skip_adding=Bit(flags,0);
const bool fix_keys=!Bit(flags,1);
//BibEntry bib;
bib.name(name);
bib.type(type);
bib.add(kvp);

if (fix_keys||true) bib.fix_keys();

if (bib.name()=="") bib.name("DUM");
if (bib.name()=="") bib.name(bib.missing_name());
MM_ERR(MMPR2(fnbib,bib.format()))
const StrTy bibtext=(bib.format());
if (fnbib.length()) { Blob b(bibtext); b.save(fnbib); } 
return 0;

} // synthesize


// parse fntemp into fntemp2 and load into j
IdxTy NewDefaultJsonScraper2(Kvp & m, Ragged & j,  const StrTy & fntemp2, const StrTy & fntemp, const StrTy & sep,const IdxTy llim, const IdxTy flags )
{
// TODO there should be a programmatic interface not cmdline 
// and this can be the new general default json scraper 
StrTy parsecmd="cat "+fntemp+"| toobib -json1 "; // +fntemp2;
//(parsecmd);
StrTy xx=fntemp2;
IdxTy rch=hand().cmd_exec(xx,StrTy(),parsecmd,8);
MM_ERR(MMPR(rch))
j.kvp_splitter(0);
j.load(fntemp2);
MM_ILOOP(i,j.size())
{
const Line & l=j[i];
const IdxTy len=l.size();
if (len<4) continue;
StrTy k=l[len-2];
const StrTy & v=l[len-1];
if (v.length()==0) continue;
int p=len-2;
// remove "global " studies and protocolsection 
//while (p>11) { p-=2; if (l[p].length()) k=l[p]+""+k;  }
while (p>int(llim)) { p-=2;if (l[p]=="GLOBAL") break;  if (l[p].length()) k=l[p]+sep+k;  }
k=StrUtil::fancy_to_lower(k);
if (m[k].length()) m[k]+=" and ";
m[k]+=l[len-1];
}


return 0;
} // NewDefaultJsonScraper2

void Init(const Ragged & r, const IdxTy start=0, const IdxTy first=0, const IdxTy flags=0  )
{
Init();
const IdxTy sz=r.size();
for(IdxTy i=start; i<sz; ++i)
{
//const Line & l=r[i];
//const IdxTy len=l.size();


}  // i 

} // Init 
void Init(const StrTy  & sin,const IdxTy flags =0  )
{
Init();
BaseParams kvp(sin);
} // Init 

void Init()
{

// m_dscope.launch_default();

m_ua="TooBib ( marchywka@hotmail.com ) ";
m_key="AIzaSyC4SFrRuMxLyGGmGs3rctWmCFQ6spLBTdc";
m_phand=DefHand();
} // Init
static Hand * DefHand() { static Hand h; return &h; } // DefHand
Hand & hand() { return *m_phand;} 

// MEMBERS
Hand* m_phand;
StrTy m_ua,m_key;

}; // mjm_goog_books

//////////////////////////////////////////////

template <class Tr>
class mjm_goog_books_map : public std::map<typename Tr::StrTy, mjm_goog_books< Tr > >  
{
 typedef mjm_goog_books_map Myt;
typedef typename std::map<typename Tr::StrTy, mjm_goog_books< Tr> >   Super;
 typedef typename Tr::IdxTy IdxTy;
 typedef typename Tr::D D;
 typedef typename Tr::StrTy StrTy;
 typedef typename Tr::Ss Ss;
 typedef typename Tr::IsTy IsTy;
 typedef typename Tr::OsTy OsTy;
 typedef typename Tr::Ofs Ofs;
//typedef typename Tr::FlagTy; 
// typedef typename Tr::MyBlock  MyBlock;
public:
mjm_goog_books_map() {}
StrTy dump(const IdxTy flags=0) { return Dump(flags); }
private:
bool Bit(const IdxTy f, const IdxTy b) const  { return  ((f>>b)&1)!=0; }
// should loop over map now 
//StrTy Dump(const IdxTy flags=0) {Ss ss;  return ss.str(); }
typedef typename mjm_thread_util<Tr>::mutex_vector MutexVector;

enum { MAP_MU=0 , MU_SZ};
mutable MutexVector m_mutex_vector;
void EnterSerial(const IdxTy i)const  {  m_mutex_vector.enter_serial(i ); }
void ExitSerial(const IdxTy i)const  {  m_mutex_vector.exit_serial(i ); }
//m_mutex_vector = MutexVector(MU_SZ);


//StrTy dump(const IdxTy flags=0) { return Dump(flags); }

private:

void Init()
{


}

StrTy Dump(const IdxTy flags=0)
{
Ss ss;
MM_LOOP(ii,(*this))
{
ss<<(*ii).first<<CRLF;
ss<<(*ii).second.dump()<<CRLF;


}
return ss.str();
// return Dump(flags); 

}




private:

}; // mjm_goog_books_map




////////////////////////////////////////////
#ifdef  TEST_MJM_GOOG_BOOKS
class Tr {
public:
// typedef mjm_string_picker Myt;
 typedef unsigned int IdxTy;
 typedef double  D;
 typedef std::string StrTy;
 typedef std::stringstream Ss;
 typedef std::istream  IsTy;
 typedef std::ostream  OsTy;
 typedef std::ofstream  Ofs;
// typedef typename Tr::MyBlock  MyBlock;
}; // 


#include "mjm_instruments.h"
#include "mjm_cli_ui.h"
typedef Tr::StrTy StrTy;
typedef Tr::IdxTy IdxTy;

template <class Tt> class tester_ {
typedef tester_<Tt> Myt;
typedef mjm_cli_ui<Myt> Cli;
//typedef tester Myt;
//typedef mjm_cli_ui<Myt> Cli;
typedef std::map<StrTy, StrTy> LocalVar;

typedef CommandInterpretterParam Cip ;
typedef void (Myt:: * CmdFunc)(Cip &, LocalVar &  ) ;
typedef std::map<StrTy, CmdFunc> CmdMap;
typedef std::vector<StrTy> Choices;
//typedef void (Myt:: * CompleteFunc) ( Cli::list_type & choices,  const char * cmd, const char * frag);
typedef void (Myt:: * CompleteFunc) ( Choices & choices,  const char * cmd, const char * frag);
typedef std::map<StrTy, CompleteFunc> CompMap;

public:
 //void cli_cmd( Cli::list_type & choices,  const char * frag)
 void cli_cmd( Choices & choices,  const char * frag)
{
const IdxTy nfrag=strlen(frag);
MM_LOOP(ii,m_cmd_map)
{
const StrTy & v=(*ii).first;
if (strncmp(v.c_str(),frag,nfrag)==0)  choices.push_back(v);
}
}

 //void cli_param( Cli::list_type & choices,  const char * _cmd, const char * frag)
 void cli_param( Choices & choices,  const char * _cmd, const char * frag)
{
MM_ERR("cli_param"<<MMPR2(_cmd,frag))
//const StrTy cmd=CliTy::word(StrTy(_cmd),0);
//auto ii=m_comp_map.find(cmd);
//if ( ii!=m_comp_map.end()) ((this)->*(*ii).second)(choices,cmd.c_str(),frag);
}

CmdMap m_cmd_map;


 }; // tester_
typedef tester_< mjm_goog_books <Tr>  > tester;

typedef mjm_cli_ui<tester> Cli;


typedef Tr::Ss Ss;

#define CI(n) atoi(cip.wif(n).c_str()) 

void about()
{
Ss ss;
ss<<" MJM_GOOG_BOOKS "<<__DATE__<<" "<<__TIME__<<CRLF;
MM_MSG(ss.str())

}
typedef mjm_ragged_table Ragged;

#define CSP(n) (cip.wif(n).c_str())
#define CIP(n) atoi(cip.wif(n).c_str())
#define CFP(n) atof(cip.wif(n).c_str())

int main(int argc,char **args)
{
about();
typedef mjm_goog_books<Tr>  Myt;
//Myt x(argc,args);
Myt x;

//if (!x.done()) x.command_mode();
Cli cli;
tester tester;
CommandInterpretter li(&std::cin);
li.push(args,argc);
cli.set_target(tester);
cli.set_command_handler(&tester::cli_cmd);
cli.set_param_handler(&tester::cli_param);
cli.activate();
li.set_split(1,' ');
while (li.nextok())
{
const IdxTy sz=li.size();
if (sz<1) continue;
const StrTy cmd=li.word(0);
if (cmd=="") continue;
if (cmd=="about"){ about();  continue; } 
CommandInterpretterParam  cip(li);

if (cmd=="loadragged") {
 	const IdxTy start=atoi(cip.wif(2).c_str()); 
	const IdxTy first=atoi(cip.wif(3).c_str()); 
	const IdxTy flags=atoi(cip.wif(4).c_str()); 
Ragged r; r.load(cip.p1); x.load(r,start,first,flags); }
if (cmd=="load") {x.load(cip.p1,atoi(cip.p2.c_str())); }
if (cmd=="save") {x.save(cip.p1,cip.p2); }
if (cmd=="test") {StrTy xxx=x.xxx_test(cip.p1,CIP(2)); MM_ERR(MMPR(xxx))  }
//IdxTy by_goog_id(const StrTy & fn, const StrTy & id, const IdxTy flags)
if (cmd=="goog") {IdxTy xxx=x.by_goog_id(cip.p1,cip.p2,CSP(3),CIP(4)); MM_ERR(MMPR(xxx))  }
if (cmd=="isbn") {IdxTy xxx=x.by_isbn(cip.p1,cip.p2,CSP(3),CSP(4),CIP(5)); MM_ERR(MMPR(xxx))  }
if (cmd=="quit") break;
// NB this does not work in gneral when errors are disabled
//if (cmd=="dump") { MM_ERR(x.dump()) }
if (cmd=="dump") { auto wtf=x.dump();  MM_ERR(wtf) }
//else if (cmd=="load") { x.load(li.words(),1); }
//else if (cmd=="clear") { x.clear(); }

} // nextok

//if (!x.done()) x.command_mode();
return 0;
}

#endif // main

#endif // MJM_GOOG_BOOKS_H__ 
